services:
  app:
    image: ghcr.io/OHsync/main-service:latest
    env_file:
      - ./apps/backend/.env.production
      - ./apps/frontend/.env.production
    ports:
      - "8080:8080"
      - "5173:5173"
    environment:
      - NODE_ENV=production
    networks:
      - app-network
    tty: true        # Keep container running
    stdin_open: true # Enable interactive mode

networks:
  app-network:
    driver: bridge