services:
  app:
    image: ghcr.io/the-office/main-service:latest
    ports:
      - "8080:8080"
      - "4173:4173"
    environment:
      - NODE_ENV=production
    networks:
      - app-network
    tty: true        # Keep container running
    stdin_open: true # Enable interactive mode

networks:
  app-network:
    driver: bridge