services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - app
    networks:
      - app-network
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  app:
    image: ghcr.io/the-office/main-service:latest
    expose:
      - "4173"
      - "8080"
    environment:
      - NODE_ENV=production
    networks:
      - app-network
    command: >
      bun install -g concurrently && 
      concurrently 
      "cd apps/backend && bun run start" 
      "cd apps/frontend && bun run preview"
      
networks:
  app-network:
    driver: bridge